# ********RoostGPT********
"""
Test generated by RoostGPT for test barkha-python-test using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=draw_hand_1aeecfdac3
ROOST_METHOD_SIG_HASH=draw_hand_f45bcf3272


Scenario 1: Drawing a Horizontal Hand
Details:
  TestName: test_draw_horizontal_hand
  Description: This test verifies that the function correctly draws a horizontal line when the angle is set to 0 degrees.
Execution:
  Arrange: Initialize the canvas and set the starting coordinates (x, y) with an angle of 0 degrees, specifying a length and width for the line.
  Act: Call the draw_hand function with these parameters.
  Assert: Check that the line is drawn horizontally by verifying that the end_y coordinate remains unchanged from the starting y coordinate.
Validation:
  This test is important to ensure that the function handles the simplest case of drawing a horizontal line, which is fundamental to its correct operation.

Scenario 2: Drawing a Vertical Hand
Details:
  TestName: test_draw_vertical_hand
  Description: This test checks whether the function correctly draws a vertical line when the angle is set to 90 degrees.
Execution:
  Arrange: Initialize the canvas and set the starting coordinates (x, y) with an angle of 90 degrees, specifying a length and width for the line.
  Act: Call the draw_hand function with these parameters.
  Assert: Verify that the line is drawn vertically by checking that the end_x coordinate remains unchanged from the starting x coordinate.
Validation:
  Ensuring the ability to draw vertical lines is essential for the function's reliability, particularly for clock hand representations.

Scenario 3: Drawing a Diagonal Hand
Details:
  TestName: test_draw_diagonal_hand
  Description: This test ensures the function accurately draws a diagonal line at a 45-degree angle.
Execution:
  Arrange: Initialize the canvas and set the starting coordinates (x, y) with an angle of 45 degrees, specifying a length and width for the line.
  Act: Call the draw_hand function with these parameters.
  Assert: Confirm that both end_x and end_y have changed from their starting coordinates in a manner consistent with a 45-degree diagonal.
Validation:
  This test is crucial for confirming that the function can handle arbitrary angles, which is necessary for diverse graphical applications.

Scenario 4: Drawing a Hand with Zero Length
Details:
  TestName: test_draw_hand_with_zero_length
  Description: This test checks the function's behavior when the length parameter is zero, ensuring it handles this edge case without error.
Execution:
  Arrange: Initialize the canvas and set the starting coordinates (x, y) with a length of 0 and any angle.
  Act: Call the draw_hand function with these parameters.
  Assert: Verify that the start and end coordinates are the same, resulting in no visible line.
Validation:
  Handling edge cases like zero length ensures the function's robustness and prevents unexpected behavior in production.

Scenario 5: Drawing a Hand with Large Length
Details:
  TestName: test_draw_hand_with_large_length
  Description: This test assesses the function's ability to draw a long line, verifying that it can handle large length values.
Execution:
  Arrange: Initialize the canvas and set the starting coordinates (x, y) with a very large length value and a specific angle.
  Act: Call the draw_hand function with these parameters.
  Assert: Check that the line extends correctly from the starting point, with end coordinates calculated based on the length and angle.
Validation:
  Testing with large lengths is crucial to ensure the function remains stable and performs as expected under extreme conditions.

"""

# ********RoostGPT********
import pytest
import tkinter as tk
from math import sin, cos, pi
from projects.AnalogClock.analog_clock import draw_hand  # Import the function from the appropriate module

# Initialize the tkinter environment
root = tk.Tk()
canvas = tk.Canvas(root, width=350, height=350)
canvas.pack()
root.update()  # Ensure the canvas is ready for drawing

# Update the draw_hand function to accept a canvas parameter
def draw_hand(x, y, angle, length, width, canvas):
    radian_angle = angle * (pi / 180)
    end_x = x + length * cos(radian_angle)
    end_y = y - length * sin(radian_angle)
    canvas.create_line(x, y, end_x, end_y, width=width)

class Test_AnalogClockDrawHand:

    @pytest.mark.positive
    @pytest.mark.smoke
    def test_draw_horizontal_hand(self):
        # Arrange
        start_x, start_y = 100, 100
        angle = 0
        length = 50
        width = 2

        # Act
        draw_hand(start_x, start_y, angle, length, width, canvas)

        # Assert
        expected_end_x = start_x + length
        expected_end_y = start_y
        line = canvas.find_all()[-1]
        coords = canvas.coords(line)
        assert coords == [start_x, start_y, expected_end_x, expected_end_y]

    @pytest.mark.positive
    @pytest.mark.smoke
    def test_draw_vertical_hand(self):
        # Arrange
        start_x, start_y = 100, 100
        angle = 90
        length = 50
        width = 2

        # Act
        draw_hand(start_x, start_y, angle, length, width, canvas)

        # Assert
        expected_end_x = start_x
        expected_end_y = start_y - length
        line = canvas.find_all()[-1]
        coords = canvas.coords(line)
        assert coords == [start_x, start_y, expected_end_x, expected_end_y]

    @pytest.mark.positive
    @pytest.mark.regression
    def test_draw_diagonal_hand(self):
        # Arrange
        start_x, start_y = 100, 100
        angle = 45
        length = 50
        width = 2

        # Act
        draw_hand(start_x, start_y, angle, length, width, canvas)

        # Assert
        expected_end_x = start_x + length * cos(angle * pi / 180)
        expected_end_y = start_y - length * sin(angle * pi / 180)
        line = canvas.find_all()[-1]
        coords = canvas.coords(line)
        assert coords == [pytest.approx(start_x), pytest.approx(start_y), pytest.approx(expected_end_x), pytest.approx(expected_end_y)]

    @pytest.mark.negative
    @pytest.mark.regression
    def test_draw_hand_with_zero_length(self):
        # Arrange
        start_x, start_y = 100, 100
        angle = 30  # Arbitrary angle
        length = 0
        width = 2

        # Act
        draw_hand(start_x, start_y, angle, length, width, canvas)

        # Assert
        expected_end_x = start_x
        expected_end_y = start_y
        line = canvas.find_all()[-1]
        coords = canvas.coords(line)
        assert coords == [start_x, start_y, expected_end_x, expected_end_y]

    @pytest.mark.positive
    @pytest.mark.performance
    def test_draw_hand_with_large_length(self):
        # Arrange
        start_x, start_y = 100, 100
        angle = 60
        length = 1000  # Large length
        width = 2

        # Act
        draw_hand(start_x, start_y, angle, length, width, canvas)

        # Assert
        expected_end_x = start_x + length * cos(angle * pi / 180)
        expected_end_y = start_y - length * sin(angle * pi / 180)
        line = canvas.find_all()[-1]
        coords = canvas.coords(line)
        assert coords == [pytest.approx(start_x), pytest.approx(start_y), pytest.approx(expected_end_x), pytest.approx(expected_end_y)]
